server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/microservices
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: HOTEL-SERVICE

  config:
    import: configserver:http://localhost:8086

#eureka:
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#  instance:
#    prefer-ip-address: true  # This line is optional, depending on your preference
#  service-url:
#    defaultZone: http://localhost:8761/eureka/